//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج با موفقیت انجام شد.
        /// </summary>
        public static string Account_Logout_Success {
            get {
                return ResourceManager.GetString("Account_Logout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ استفاده از این کد تخفیف به پایان رسیده است.
        /// </summary>
        public static string Expired_DiscountCode {
            get {
                return ResourceManager.GetString("Expired_DiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در نمایش اطلاعات.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودیت در ارسال رمز عبور.
        /// </summary>
        public static string ForgetPassword_SenLimit {
            get {
                return ResourceManager.GetString("ForgetPassword_SenLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک فراموشی رمز عبور ارسال شد..
        /// </summary>
        public static string ForgetPassword_SmsSentSuccessfully {
            get {
                return ResourceManager.GetString("ForgetPassword_SmsSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا موارد ضروری را تکمیل کنید.
        /// </summary>
        public static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف معتبر نمی باشد.
        /// </summary>
        public static string Invalid_DiscountCode {
            get {
                return ResourceManager.GetString("Invalid_DiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور و تکرار آن مشابه نیستند.
        /// </summary>
        public static string InvalidNewPass {
            get {
                return ResourceManager.GetString("InvalidNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما پکیج فعالی برای پرسش و پاسخ ندارید.
        /// </summary>
        public static string InvalidPackage {
            get {
                return ResourceManager.GetString("InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور اشتباه است.
        /// </summary>
        public static string InvalidPass {
            get {
                return ResourceManager.GetString("InvalidPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما پیکج فعال برای پرسش و پاسخ دارید و نمی توانید پکیج جدید خریداری کنید.
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر وارد شده یافت نشد..
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول وارد شده یافت نشد.
        /// </summary>
        public static string InvaliProductId {
            get {
                return ResourceManager.GetString("InvaliProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ورود.
        /// </summary>
        public static string Login_BadRequest {
            get {
                return ResourceManager.GetString("Login_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با موفقیت انجام شد.
        /// </summary>
        public static string Login_SuccessLogin {
            get {
                return ResourceManager.GetString("Login_SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده صحیح نمی باشد..
        /// </summary>
        public static string MobilExpersionValidation {
            get {
                return ResourceManager.GetString("MobilExpersionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعالسازی وارد شده صحیح نمی باشد..
        /// </summary>
        public static string Registe_WrongActivationCode {
            get {
                return ResourceManager.GetString("Registe_WrongActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده تکراری می باشد..
        /// </summary>
        public static string Register_DuplicateCellNumber {
            get {
                return ResourceManager.GetString("Register_DuplicateCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودیت در ارسال کد فعالسازی.
        /// </summary>
        public static string Register_ResendActivationCodeLimit {
            get {
                return ResourceManager.GetString("Register_ResendActivationCodeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام با موفقیت انجام شد.
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما با موفقت فعال شد..
        /// </summary>
        public static string Register_SuccessActivate {
            get {
                return ResourceManager.GetString("Register_SuccessActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعالسازی ارسال گردید..
        /// </summary>
        public static string Register_SuccessResendCode {
            get {
                return ResourceManager.GetString("Register_SuccessResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش موفق اطلاعات.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف کاربر با موفقیت انجام شد.
        /// </summary>
        public static string Success_DeleteUser {
            get {
                return ResourceManager.GetString("Success_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات با موفقیت انجام شد.
        /// </summary>
        public static string SuccessPost {
            get {
                return ResourceManager.GetString("SuccessPost", resourceCulture);
            }
        }
    }
}
